### ISSUE TITLE
Interfaz gráfica Menú C#

### ISSUE THREAD

**Issue by OFELHER93** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-topicosadobexd#1]

**Comment by SantiagoCoronelJoanna** [comment]
[interfaz grafica C#.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-topicosadobexd/files/8122219/interfaz.grafica.C.pdf)

**Comment by josealfredo79** [comment]
y la calificación..????

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by Yareli-Perez** [comment]
calificación = 90

**Comment by josealfredo79** [comment]
La calificación deben aplicar una regla de 3 sobre la calificación máxima de 20%
